//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Haskellmm.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class HaskellmmParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, IF=8, THEN=9, 
		ELSE=10, NEWLINE=11, INT=12, BOOL=13, CHAR=14, F_NAME=15, R_VAR=16, WS=17;
	public const int
		RULE_prog = 0, RULE_expr = 1, RULE_f_defi = 2, RULE_ite_defi = 3;
	public static readonly string[] ruleNames = {
		"prog", "expr", "f_defi", "ite_defi"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'*'", "'/'", "'+'", "'-'", "'='", "'if'", "'then'", 
		"'else'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, "IF", "THEN", "ELSE", 
		"NEWLINE", "INT", "BOOL", "CHAR", "F_NAME", "R_VAR", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Haskellmm.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static HaskellmmParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public HaskellmmParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public HaskellmmParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class ProgContext : ParserRuleContext {
		public F_defiContext[] f_defi() {
			return GetRuleContexts<F_defiContext>();
		}
		public F_defiContext f_defi(int i) {
			return GetRuleContext<F_defiContext>(i);
		}
		public ITerminalNode[] NEWLINE() { return GetTokens(HaskellmmParser.NEWLINE); }
		public ITerminalNode NEWLINE(int i) {
			return GetToken(HaskellmmParser.NEWLINE, i);
		}
		public ProgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.EnterProg(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.ExitProg(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHaskellmmVisitor<TResult> typedVisitor = visitor as IHaskellmmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgContext prog() {
		ProgContext _localctx = new ProgContext(Context, State);
		EnterRule(_localctx, 0, RULE_prog);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 17;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==F_NAME) {
				{
				{
				State = 8; f_defi();
				State = 12;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==NEWLINE) {
					{
					{
					State = 9; Match(NEWLINE);
					}
					}
					State = 14;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				}
				State = 19;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class RefVarContext : ExprContext {
		public ITerminalNode[] R_VAR() { return GetTokens(HaskellmmParser.R_VAR); }
		public ITerminalNode R_VAR(int i) {
			return GetToken(HaskellmmParser.R_VAR, i);
		}
		public RefVarContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.EnterRefVar(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.ExitRefVar(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHaskellmmVisitor<TResult> typedVisitor = visitor as IHaskellmmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRefVar(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntVarContext : ExprContext {
		public ITerminalNode INT() { return GetToken(HaskellmmParser.INT, 0); }
		public IntVarContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.EnterIntVar(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.ExitIntVar(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHaskellmmVisitor<TResult> typedVisitor = visitor as IHaskellmmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntVar(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MultExpContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public MultExpContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.EnterMultExp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.ExitMultExp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHaskellmmVisitor<TResult> typedVisitor = visitor as IHaskellmmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParenExpContext : ExprContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ParenExpContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.EnterParenExp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.ExitParenExp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHaskellmmVisitor<TResult> typedVisitor = visitor as IHaskellmmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParenExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AddExpContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public AddExpContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.EnterAddExp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.ExitAddExp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHaskellmmVisitor<TResult> typedVisitor = visitor as IHaskellmmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAddExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IteExpContext : ExprContext {
		public Ite_defiContext ite_defi() {
			return GetRuleContext<Ite_defiContext>(0);
		}
		public IteExpContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.EnterIteExp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.ExitIteExp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHaskellmmVisitor<TResult> typedVisitor = visitor as IHaskellmmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIteExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 2;
		EnterRecursionRule(_localctx, 2, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 32;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
				{
				_localctx = new ParenExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 21; Match(T__0);
				State = 22; expr(0);
				State = 23; Match(T__1);
				}
				break;
			case R_VAR:
				{
				_localctx = new RefVarContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 26;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 25; Match(R_VAR);
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 28;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				}
				break;
			case IF:
				{
				_localctx = new IteExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 30; ite_defi();
				}
				break;
			case INT:
				{
				_localctx = new IntVarContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 31; Match(INT);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 42;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 40;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
					case 1:
						{
						_localctx = new MultExpContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 34;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 35;
						_la = TokenStream.LA(1);
						if ( !(_la==T__2 || _la==T__3) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 36; expr(4);
						}
						break;
					case 2:
						{
						_localctx = new AddExpContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 37;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 38;
						_la = TokenStream.LA(1);
						if ( !(_la==T__4 || _la==T__5) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 39; expr(3);
						}
						break;
					}
					} 
				}
				State = 44;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class F_defiContext : ParserRuleContext {
		public ITerminalNode F_NAME() { return GetToken(HaskellmmParser.F_NAME, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode[] R_VAR() { return GetTokens(HaskellmmParser.R_VAR); }
		public ITerminalNode R_VAR(int i) {
			return GetToken(HaskellmmParser.R_VAR, i);
		}
		public F_defiContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_f_defi; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.EnterF_defi(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.ExitF_defi(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHaskellmmVisitor<TResult> typedVisitor = visitor as IHaskellmmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitF_defi(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public F_defiContext f_defi() {
		F_defiContext _localctx = new F_defiContext(Context, State);
		EnterRule(_localctx, 4, RULE_f_defi);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 45; Match(F_NAME);
			State = 49;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==R_VAR) {
				{
				{
				State = 46; Match(R_VAR);
				}
				}
				State = 51;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 52; Match(T__6);
			State = 53; expr(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ite_defiContext : ParserRuleContext {
		public ITerminalNode IF() { return GetToken(HaskellmmParser.IF, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode THEN() { return GetToken(HaskellmmParser.THEN, 0); }
		public ITerminalNode ELSE() { return GetToken(HaskellmmParser.ELSE, 0); }
		public Ite_defiContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ite_defi; } }
		public override void EnterRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.EnterIte_defi(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IHaskellmmListener typedListener = listener as IHaskellmmListener;
			if (typedListener != null) typedListener.ExitIte_defi(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHaskellmmVisitor<TResult> typedVisitor = visitor as IHaskellmmVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIte_defi(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Ite_defiContext ite_defi() {
		Ite_defiContext _localctx = new Ite_defiContext(Context, State);
		EnterRule(_localctx, 6, RULE_ite_defi);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 55; Match(IF);
			State = 56; expr(0);
			State = 57; Match(THEN);
			State = 58; expr(0);
			State = 59; Match(ELSE);
			State = 60; expr(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 1: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 3);
		case 1: return Precpred(Context, 2);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x13', '\x41', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x3', 
		'\x2', '\x3', '\x2', '\a', '\x2', '\r', '\n', '\x2', '\f', '\x2', '\xE', 
		'\x2', '\x10', '\v', '\x2', '\a', '\x2', '\x12', '\n', '\x2', '\f', '\x2', 
		'\xE', '\x2', '\x15', '\v', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x6', '\x3', '\x1D', 
		'\n', '\x3', '\r', '\x3', '\xE', '\x3', '\x1E', '\x3', '\x3', '\x3', '\x3', 
		'\x5', '\x3', '#', '\n', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', '+', '\n', '\x3', 
		'\f', '\x3', '\xE', '\x3', '.', '\v', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\a', '\x4', '\x32', '\n', '\x4', '\f', '\x4', '\xE', '\x4', '\x35', '\v', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x2', '\x3', '\x4', '\x6', '\x2', '\x4', '\x6', 
		'\b', '\x2', '\x4', '\x3', '\x2', '\x5', '\x6', '\x3', '\x2', '\a', '\b', 
		'\x2', '\x45', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x4', '\"', 
		'\x3', '\x2', '\x2', '\x2', '\x6', '/', '\x3', '\x2', '\x2', '\x2', '\b', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\n', '\xE', '\x5', '\x6', '\x4', 
		'\x2', '\v', '\r', '\a', '\r', '\x2', '\x2', '\f', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\r', '\x10', '\x3', '\x2', '\x2', '\x2', '\xE', '\f', '\x3', 
		'\x2', '\x2', '\x2', '\xE', '\xF', '\x3', '\x2', '\x2', '\x2', '\xF', 
		'\x12', '\x3', '\x2', '\x2', '\x2', '\x10', '\xE', '\x3', '\x2', '\x2', 
		'\x2', '\x11', '\n', '\x3', '\x2', '\x2', '\x2', '\x12', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x13', '\x11', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'\x14', '\x3', '\x2', '\x2', '\x2', '\x14', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x15', '\x13', '\x3', '\x2', '\x2', '\x2', '\x16', '\x17', '\b', 
		'\x3', '\x1', '\x2', '\x17', '\x18', '\a', '\x3', '\x2', '\x2', '\x18', 
		'\x19', '\x5', '\x4', '\x3', '\x2', '\x19', '\x1A', '\a', '\x4', '\x2', 
		'\x2', '\x1A', '#', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x1D', '\a', 
		'\x12', '\x2', '\x2', '\x1C', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\x1E', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', '\x1E', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x1F', '#', '\x3', 
		'\x2', '\x2', '\x2', ' ', '#', '\x5', '\b', '\x5', '\x2', '!', '#', '\a', 
		'\xE', '\x2', '\x2', '\"', '\x16', '\x3', '\x2', '\x2', '\x2', '\"', '\x1C', 
		'\x3', '\x2', '\x2', '\x2', '\"', ' ', '\x3', '\x2', '\x2', '\x2', '\"', 
		'!', '\x3', '\x2', '\x2', '\x2', '#', ',', '\x3', '\x2', '\x2', '\x2', 
		'$', '%', '\f', '\x5', '\x2', '\x2', '%', '&', '\t', '\x2', '\x2', '\x2', 
		'&', '+', '\x5', '\x4', '\x3', '\x6', '\'', '(', '\f', '\x4', '\x2', '\x2', 
		'(', ')', '\t', '\x3', '\x2', '\x2', ')', '+', '\x5', '\x4', '\x3', '\x5', 
		'*', '$', '\x3', '\x2', '\x2', '\x2', '*', '\'', '\x3', '\x2', '\x2', 
		'\x2', '+', '.', '\x3', '\x2', '\x2', '\x2', ',', '*', '\x3', '\x2', '\x2', 
		'\x2', ',', '-', '\x3', '\x2', '\x2', '\x2', '-', '\x5', '\x3', '\x2', 
		'\x2', '\x2', '.', ',', '\x3', '\x2', '\x2', '\x2', '/', '\x33', '\a', 
		'\x11', '\x2', '\x2', '\x30', '\x32', '\a', '\x12', '\x2', '\x2', '\x31', 
		'\x30', '\x3', '\x2', '\x2', '\x2', '\x32', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\x31', '\x3', '\x2', '\x2', '\x2', '\x33', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\x34', '\x36', '\x3', '\x2', '\x2', '\x2', '\x35', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x36', '\x37', '\a', '\t', '\x2', 
		'\x2', '\x37', '\x38', '\x5', '\x4', '\x3', '\x2', '\x38', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x39', ':', '\a', '\n', '\x2', '\x2', ':', ';', 
		'\x5', '\x4', '\x3', '\x2', ';', '<', '\a', '\v', '\x2', '\x2', '<', '=', 
		'\x5', '\x4', '\x3', '\x2', '=', '>', '\a', '\f', '\x2', '\x2', '>', '?', 
		'\x5', '\x4', '\x3', '\x2', '?', '\t', '\x3', '\x2', '\x2', '\x2', '\t', 
		'\xE', '\x13', '\x1E', '\"', '*', ',', '\x33',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
