//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Haskellmm.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="HaskellmmParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IHaskellmmVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="HaskellmmParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] HaskellmmParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>refVar</c>
	/// labeled alternative in <see cref="HaskellmmParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefVar([NotNull] HaskellmmParser.RefVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>boolVar</c>
	/// labeled alternative in <see cref="HaskellmmParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolVar([NotNull] HaskellmmParser.BoolVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>intVar</c>
	/// labeled alternative in <see cref="HaskellmmParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntVar([NotNull] HaskellmmParser.IntVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multExp</c>
	/// labeled alternative in <see cref="HaskellmmParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultExp([NotNull] HaskellmmParser.MultExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>compExp</c>
	/// labeled alternative in <see cref="HaskellmmParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompExp([NotNull] HaskellmmParser.CompExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parenExp</c>
	/// labeled alternative in <see cref="HaskellmmParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenExp([NotNull] HaskellmmParser.ParenExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>addExp</c>
	/// labeled alternative in <see cref="HaskellmmParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddExp([NotNull] HaskellmmParser.AddExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>iteExp</c>
	/// labeled alternative in <see cref="HaskellmmParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIteExp([NotNull] HaskellmmParser.IteExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HaskellmmParser.f_defi"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitF_defi([NotNull] HaskellmmParser.F_defiContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HaskellmmParser.ite_defi"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIte_defi([NotNull] HaskellmmParser.Ite_defiContext context);
}
